from common import *

# Operands
Eb = Operand("Eb", OperandSize.Byte, OperandMode.ModRM_RM)
Ev = Operand("Ev", OperandSize.Auto, OperandMode.ModRM_RM)
Ew = Operand("Ew", OperandSize.Word, OperandMode.ModRM_RM)
Gb = Operand("Gb", OperandSize.Byte, OperandMode.ModRM_Reg)
Gw = Operand("Gw", OperandSize.Word, OperandMode.ModRM_Reg)
Gv = Operand("Gv", OperandSize.Auto, OperandMode.ModRM_Reg)
Sw = Operand("Sw", OperandSize.Word, OperandMode.ModRM_SegmentRegister)
Ib = Operand("Ib", OperandSize.Byte, OperandMode.Immediate)
Iw = Operand("Iw", OperandSize.Word, OperandMode.Immediate)
Iv = Operand("Iv", OperandSize.Auto, OperandMode.Immediate)
Ib2 = Operand("Ib2", OperandSize.Byte, OperandMode.Immediate2)
Iw2 = Operand("Iw2", OperandSize.Word, OperandMode.Immediate2)
Iv2 = Operand("Iv2", OperandSize.Auto, OperandMode.Immediate2)
M = Operand("M", OperandSize.Auto, OperandMode.ModRM_RM)
Ap = Operand("Ap", OperandSize.Auto, OperandMode.FarAddress)
Mp = Operand("Mp", OperandSize.Auto, OperandMode.ModRM_RM)
Mw = Operand("Mw", OperandSize.Word, OperandMode.ModRM_RM)
Md = Operand("Md", OperandSize.DWord, OperandMode.ModRM_RM)
Mq = Operand("Mq", OperandSize.QWord, OperandMode.ModRM_RM)
Mt = Operand("Mt", OperandSize.TWord, OperandMode.ModRM_RM)
Ob = Operand("Ob", OperandSize.Byte, OperandMode.Memory)
Ow = Operand("Ow", OperandSize.Word, OperandMode.Memory)
Ov = Operand("Ov", OperandSize.Auto, OperandMode.Memory)
Jb = Operand("Jb", OperandSize.Byte, OperandMode.Relative)
Jw = Operand("Jw", OperandSize.Word, OperandMode.Relative)
Jv = Operand("Jv", OperandSize.Auto, OperandMode.Relative)


def Cb(n):
    return Operand("Cb(%d)" % n, OperandSize.Byte, OperandMode.Constant, n)


def Cw(n):
    return Operand("Cw(%d)" % n, OperandSize.Word, OperandMode.Constant, n)


def Cv(n):
    return Operand("Cv(%d)" % n, OperandSize.Auto, OperandMode.Constant, n)


Ms = Operand("Ms", OperandSize.Word, OperandMode.ModRM_RM)
Ma = Operand("Ma", OperandSize.Word, OperandMode.ModRM_RM)
Cd = Operand("Cd", OperandSize.DWord, OperandMode.ModRM_ControlRegister)
Td = Operand("Td", OperandSize.DWord, OperandMode.ModRM_TestRegister)
Dd = Operand("Dd", OperandSize.DWord, OperandMode.ModRM_DebugRegister)
Rd = Operand("Rd", OperandSize.DWord, OperandMode.ModRM_RM)
Xb = Operand("Xb", OperandSize.Byte, OperandMode.RegisterIndirect, Reg32.ESI)
Xw = Operand("Xw", OperandSize.Word, OperandMode.RegisterIndirect, Reg16.SI)
Xv = Operand("Xv", OperandSize.Auto, OperandMode.RegisterIndirect, Reg32.ESI)
Yb = Operand("Yb", OperandSize.Byte, OperandMode.RegisterIndirect, Reg32.EDI)
Yw = Operand("Yw", OperandSize.Word, OperandMode.RegisterIndirect, Reg16.DI)
Yv = Operand("Yv", OperandSize.Auto, OperandMode.RegisterIndirect, Reg32.EDI)
AL = Operand("AL", OperandSize.Byte, OperandMode.Register, Reg8.AL)
AH = Operand("AH", OperandSize.Byte, OperandMode.Register, Reg8.AH)
CL = Operand("CL", OperandSize.Byte, OperandMode.Register, Reg8.CL)
CH = Operand("CH", OperandSize.Byte, OperandMode.Register, Reg8.CH)
DL = Operand("DL", OperandSize.Byte, OperandMode.Register, Reg8.DL)
DH = Operand("DH", OperandSize.Byte, OperandMode.Register, Reg8.DH)
BL = Operand("BL", OperandSize.Byte, OperandMode.Register, Reg8.BL)
BH = Operand("BH", OperandSize.Byte, OperandMode.Register, Reg8.BH)
AX = Operand("AX", OperandSize.Word, OperandMode.Register, Reg16.AX)
CX = Operand("CX", OperandSize.Word, OperandMode.Register, Reg16.CX)
DX = Operand("DX", OperandSize.Word, OperandMode.Register, Reg16.DX)
BX = Operand("BX", OperandSize.Word, OperandMode.Register, Reg16.BX)
SP = Operand("SP", OperandSize.Word, OperandMode.Register, Reg16.SP)
BP = Operand("BP", OperandSize.Word, OperandMode.Register, Reg16.BP)
SI = Operand("SI", OperandSize.Word, OperandMode.Register, Reg16.SI)
DI = Operand("DI", OperandSize.Word, OperandMode.Register, Reg16.DI)
EAX = Operand("EAX", OperandSize.DWord, OperandMode.Register, Reg32.EAX)
ECX = Operand("ECX", OperandSize.DWord, OperandMode.Register, Reg32.ECX)
EDX = Operand("EDX", OperandSize.DWord, OperandMode.Register, Reg32.EDX)
EBX = Operand("EBX", OperandSize.DWord, OperandMode.Register, Reg32.EBX)
ESP = Operand("ESP", OperandSize.DWord, OperandMode.Register, Reg32.ESP)
EBP = Operand("EBP", OperandSize.DWord, OperandMode.Register, Reg32.EBP)
ESI = Operand("ESI", OperandSize.DWord, OperandMode.Register, Reg32.ESI)
EDI = Operand("EDI", OperandSize.DWord, OperandMode.Register, Reg32.EDI)
eAX = Operand("eAX", OperandSize.Auto, OperandMode.Register, Reg32.EAX)
eCX = Operand("eCX", OperandSize.Auto, OperandMode.Register, Reg32.ECX)
eDX = Operand("eDX", OperandSize.Auto, OperandMode.Register, Reg32.EDX)
eBX = Operand("eBX", OperandSize.Auto, OperandMode.Register, Reg32.EBX)
eSP = Operand("eSP", OperandSize.Auto, OperandMode.Register, Reg32.ESP)
eBP = Operand("eBP", OperandSize.Auto, OperandMode.Register, Reg32.EBP)
eSI = Operand("eSI", OperandSize.Auto, OperandMode.Register, Reg32.ESI)
eDI = Operand("eDI", OperandSize.Auto, OperandMode.Register, Reg32.EDI)
CS = Operand("CS", OperandSize.Word, OperandMode.SegmentRegister, Segment.CS)
DS = Operand("DS", OperandSize.Word, OperandMode.SegmentRegister, Segment.DS)
ES = Operand("ES", OperandSize.Word, OperandMode.SegmentRegister, Segment.ES)
SS = Operand("SS", OperandSize.Word, OperandMode.SegmentRegister, Segment.SS)
FS = Operand("FS", OperandSize.Word, OperandMode.SegmentRegister, Segment.FS)
GS = Operand("GS", OperandSize.Word, OperandMode.SegmentRegister, Segment.GS)


def ST(n):
    return Operand("ST(%d)" % n, OperandSize.TWord, OperandMode.FPRegister, n)
